'use strict'

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Products',
      [
        {
          name: 'Asus ROG Zephyrush M16',
          description: 'Laptop gaming dari asus',
          category_id: 1,
          sold: 0,
          price: 30000000,
          stock: 20,
          cover_imageID : 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Macbook pro M2',
          description: 'Laptop gaming dari apple',
          category_id: 1,
          sold: 0,
          price: 25000000,
          stock: 30,
          cover_imageID : 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'ASUS Zenbook Pro 15 OLED UX535',
          description: 'Laptop dari asus',
          category_id: 1,
          sold: 0,
          price: 24000000,
          stock: 50,
          cover_imageID : 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lenovo Yoga Duet 7i',
          description: 'Laptop dari lenovo',
          category_id: 1,
          sold: 0,
          price: 20000000,
          stock: 50,
          cover_imageID : 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'HP Spectre X360 am0231TU',
          description: 'Laptop dari HP',
          category_id: 1,
          sold: 0,
          price: 24000000,
          stock: 25,
          cover_imageID : 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Samsung S22 Ultra',
          description: 'Smarphone dari samsung',
          category_id: 2,
          sold: 0,
          price: 24000000,
          stock: 5,
          cover_imageID : 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Iphone 13 Pro',
          description: 'Smarphone dari apple',
          category_id: 2,
          sold: 0,
          price: 23000000,
          stock: 10,
          cover_imageID : 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'ASUS ROG Phone 6 Pro 18/512Gb',
          description: 'Smarphone dari asus',
          category_id: 2,
          sold: 0,
          price: 26500000,
          stock: 10,
          cover_imageID : 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Xiomi 12 Pro 12GB/256GB',
          description: 'Smarphone dari xiomi',
          category_id: 2,
          sold: 0,
          price: 13000000,
          stock: 10,
          cover_imageID : 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    )
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Products', null, {})
  },
}
