version: '2.2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5431:5432'
    expose:
      - '5432'
    networks:
      - elastic
  
  platinum:
    build: .
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - elastic
    depends_on:
      - postgres

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge